"use client";

import { useState, useEffect } from 'react';
import dynamic from 'next/dynamic';

// Dynamically import heavy components to avoid SSR issues
const HonestAIPipeline = dynamic(() => import('./components/HonestAIPipeline'), {
  ssr: false,
  loading: () => (
    <div className="bg-white rounded-2xl shadow-xl p-6">
      <div className="animate-pulse">
        <div className="h-8 bg-gray-200 rounded w-1/3 mb-6"></div>
        <div className="h-32 bg-gray-200 rounded mb-4"></div>
        <div className="h-10 bg-gray-200 rounded"></div>
      </div>
    </div>
  )
});

const FullStackFactory = dynamic(() => import('./components/FullStackFactory'), {
  ssr: false,
  loading: () => (
    <div className="bg-white rounded-2xl shadow-xl p-6">
      <div className="animate-pulse">
        <div className="h-8 bg-gray-200 rounded w-1/3 mb-6"></div>
        <div className="h-32 bg-gray-200 rounded mb-4"></div>
        <div className="h-10 bg-gray-200 rounded"></div>
      </div>
    </div>
  )
});

const EnhancedCanvasPanel = dynamic(() => import('./components/canvas/EnhancedCanvasPanel'), {
  ssr: false,
  loading: () => (
    <div className="h-[600px] bg-gray-900 rounded-xl animate-pulse flex items-center justify-center">
      <div className="text-gray-400">Loading AI Canvas IDE...</div>
    </div>
  )
});

type TabType = 'component' | 'fullstack' | 'canvas' | 'code' | 'export';
type ModeType = 'nextjs' | 'react' | 'flutter' | 'node' | 'python';

// Base files for the canvas
const baseFiles: Record<string, string> = {
  'App.tsx': `import React from 'react';
import AIComponent from './components/AIComponent';

export default function App() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 to-black text-white">
      <header className="container mx-auto px-4 py-8">
        <h1 className="text-4xl font-bold">AI Meta Factory Project</h1>
        <p className="text-gray-400 mt-2">Built with Next.js, TypeScript, and AI</p>
      </header>
      
      <main className="container mx-auto px-4 py-8">
        <AIComponent 
          title="Welcome to AI Meta Factory"
          description="This is an AI-generated component. Edit or add new components using the AI Assistant."
        />
        
        <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-gray-800 rounded-xl p-6">
            <h2 className="text-2xl font-bold mb-4">🚀 Features</h2>
            <ul className="space-y-2">
              <li className="flex items-center gap-2">
                <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                <span>AI-Powered Component Generation</span>
              </li>
              <li className="flex items-center gap-2">
                <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                <span>Real-time Code Editor</span>
              </li>
              <li className="flex items-center gap-2">
                <div className="w-2 h-2 bg-purple-500 rounded-full"></div>
                <span>Live Preview</span>
              </li>
            </ul>
          </div>
          
          <div className="bg-gray-800 rounded-xl p-6">
            <h2 className="text-2xl font-bold mb-4">🛠️ Stack</h2>
            <div className="flex flex-wrap gap-2">
              <span className="px-3 py-1 bg-blue-900/50 text-blue-300 rounded-full text-sm">Next.js 14</span>
              <span className="px-3 py-1 bg-green-900/50 text-green-300 rounded-full text-sm">TypeScript</span>
              <span className="px-3 py-1 bg-purple-900/50 text-purple-300 rounded-full text-sm">Tailwind CSS</span>
              <span className="px-3 py-1 bg-yellow-900/50 text-yellow-300 rounded-full text-sm">AI Integration</span>
            </div>
          </div>
        </div>
      </main>
      
      <footer className="container mx-auto px-4 py-8 mt-12 border-t border-gray-800">
        <p className="text-gray-500 text-center">
          Built with ❤️ by AI Meta Factory • {new Date().getFullYear()}
        </p>
      </footer>
    </div>
  );
}`,

  'components/AIComponent.tsx': `import React from 'react';

interface AIComponentProps {
  title: string;
  description?: string;
  className?: string;
}

export default function AIComponent({ 
  title, 
  description = "This component was generated by AI",
  className = ''
}: AIComponentProps) {
  return (
    <div className={\`ai-component bg-gradient-to-br from-gray-800 to-gray-900 rounded-2xl p-8 shadow-2xl \${className}\`}>
      <div className="flex items-center justify-between mb-6">
        <h2 className="text-3xl font-bold">{title}</h2>
        <div className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-purple-600 to-pink-600 rounded-full">
          <span className="text-lg">🤖</span>
          <span className="font-bold">AI Generated</span>
        </div>
      </div>
      
      <p className="text-gray-300 mb-6 text-lg">
        {description}
      </p>
      
      <div className="flex flex-wrap gap-4">
        <button className="px-6 py-3 bg-gradient-to-r from-blue-600 to-blue-700 rounded-lg font-bold hover:opacity-90 transition">
          Edit Component
        </button>
        <button className="px-6 py-3 bg-gray-700 rounded-lg font-bold hover:bg-gray-600 transition">
          View Code
        </button>
        <button className="px-6 py-3 bg-gradient-to-r from-green-600 to-emerald-700 rounded-lg font-bold hover:opacity-90 transition">
          Generate New
        </button>
      </div>
      
      <div className="mt-8 pt-6 border-t border-gray-700">
        <div className="flex items-center gap-3 text-sm text-gray-400">
          <div className="flex items-center gap-1">
            <div className="w-3 h-3 rounded-full bg-blue-500"></div>
            <span>React</span>
          </div>
          <div className="flex items-center gap-1">
            <div className="w-3 h-3 rounded-full bg-green-500"></div>
            <span>TypeScript</span>
          </div>
          <div className="flex items-center gap-1">
            <div className="w-3 h-3 rounded-full bg-purple-500"></div>
            <span>Tailwind CSS</span>
          </div>
        </div>
      </div>
    </div>
  );
}`,

  'styles/globals.css': `/* Global Styles for AI Meta Factory */

@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
  }
  
  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
  }
}

@layer components {
  .ai-component {
    transition: all 0.3s ease;
  }
  
  .ai-component:hover {
    transform: translateY(-2px);
    box-shadow: 0 20px 40px rgba(0, 0, 0, 0.3);
  }
  
  .code-block {
    @apply bg-gray-900 text-gray-300 font-mono text-sm rounded-lg p-4 overflow-x-auto;
  }
  
  .gradient-text {
    @apply bg-clip-text text-transparent bg-gradient-to-r from-blue-500 to-purple-500;
  }
}`,

  'package.json': `{
  "name": "ai-meta-factory-project",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.0.0",
    "react": "^18",
    "react-dom": "^18",
    "lucide-react": "^0.321.0",
    "tailwindcss": "^3.3.0",
    "autoprefixer": "^10.0.0",
    "postcss": "^8.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5.0.0"
  }
}`,

  'tailwind.config.js': `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
      },
      animation: {
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        }
      }
    },
  },
  plugins: [],
}`,

  'README.md': `# AI Meta Factory Project

This project was generated using the AI Meta Factory platform.

## 🚀 Features

- AI-powered component generation
- Real-time code editing with Monaco Editor
- Live preview with Sandpack
- Full-stack project generation
- Export to GitHub/Vercel

## 🛠️ Tech Stack

- **Frontend:** Next.js 14 with TypeScript
- **Styling:** Tailwind CSS
- **Database:** Supabase (configured)
- **Git Provider:** GitHub

## 📁 Project Structure

\`\`\`
.
├── App.tsx              # Main application component
├── components/          # React components
│   └── AIComponent.tsx  # AI-generated component
├── styles/              # Global styles
│   └── globals.css
├── package.json         # Dependencies
├── tailwind.config.js   # Tailwind config
└── README.md
\`\`\`

## 🚦 Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Run development server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Open [http://localhost:3000](http://localhost:3000)

## 🤖 AI Assistant

Use the AI Assistant in the canvas to:
- Generate new components
- Refactor existing code
- Add new features
- Fix bugs

## 📦 Export Options

- Download as ZIP
- Push to GitHub
- Deploy to Vercel

---

Built with ❤️ by AI Meta Factory
`
};

// Simple StackConfig type to avoid import issues
interface StackConfig {
  frontend: 'nextjs' | 'react' | 'flutter';
  backend: 'nodejs' | 'python' | 'none';
  database: 'supabase' | 'firebase' | 'mongodb' | 'planetscale' | 'none';
  gitProvider: 'github' | 'gitlab' | 'bitbucket';
}

export default function BuilderPage() {
  const [activeTab, setActiveTab] = useState<TabType>('component');
  const [mode, setMode] = useState<ModeType>('nextjs');
  const [database, setDatabase] = useState('supabase');
  const [gitProvider, setGitProvider] = useState('github');
  const [connectedGit, setConnectedGit] = useState(false);
  const [isConfiguring, setIsConfiguring] = useState(false);
  const [generatedFiles, setGeneratedFiles] = useState<Record<string, string>>({});

  const modeConfigs = {
    nextjs: { name: 'Next.js', icon: '⚡', color: 'from-black to-gray-800' },
    react: { name: 'React', icon: '⚛️', color: 'from-blue-500 to-blue-700' },
    flutter: { name: 'Flutter', icon: '📱', color: 'from-blue-400 to-sky-500' },
    node: { name: 'Node.js', icon: '🟢', color: 'from-green-600 to-green-800' },
    python: { name: 'Python', icon: '🐍', color: 'from-yellow-500 to-blue-500' }
  };

  const databaseConfigs = {
    supabase: { name: 'Supabase', icon: '🟢', color: 'from-green-500 to-emerald-600' },
    firebase: { name: 'Firebase', icon: '🟠', color: 'from-orange-500 to-yellow-500' },
    mongodb: { name: 'MongoDB', icon: '🍃', color: 'from-green-600 to-green-400' },
    planetscale: { name: 'PlanetScale', icon: '🟣', color: 'from-purple-500 to-pink-500' },
    none: { name: 'No Database', icon: '⚪', color: 'from-gray-400 to-gray-600' }
  };

  const gitConfigs = {
    github: { name: 'GitHub', icon: '🐙', color: 'from-gray-800 to-gray-900' },
    gitlab: { name: 'GitLab', icon: '🦊', color: 'from-orange-600 to-red-500' },
    bitbucket: { name: 'BitBucket', icon: '🐋', color: 'from-blue-600 to-blue-800' }
  };

  // Build stack config for EnhancedCanvasPanel
  const getStackConfig = (): StackConfig => {
    let frontend: 'nextjs' | 'react' | 'flutter' = 'nextjs';
    let backend: 'nodejs' | 'python' | 'none' = 'none';
    
    // Map mode to frontend/backend
    if (mode === 'nextjs' || mode === 'react' || mode === 'flutter') {
      frontend = mode as 'nextjs' | 'react' | 'flutter';
      backend = 'nodejs'; // Default backend for frontend frameworks
    } else if (mode === 'node') {
      frontend = 'react'; // Default frontend for node
      backend = 'nodejs';
    } else if (mode === 'python') {
      frontend = 'react'; // Default frontend for python
      backend = 'python';
    }
    
    return {
      frontend,
      backend,
      database: database as StackConfig['database'],
      gitProvider: gitProvider as StackConfig['gitProvider']
    };
  };

  const connectGitHub = () => {
    setIsConfiguring(true);
    setTimeout(() => {
      setConnectedGit(true);
      setIsConfiguring(false);
      console.log('✅ GitHub connected!');
    }, 1500);
  };

  const exportProject = () => {
    if (!connectedGit) {
      alert('⚠️ Connect GitHub first to export projects.');
      return;
    }
    alert(`🚀 Exporting ${modeConfigs[mode].name} project with ${databaseConfigs[database].name} to ${gitConfigs[gitProvider].name}...`);
  };

  const handleFilesChange = (files: Record<string, string>) => {
    setGeneratedFiles(files);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50">
      {/* Header */}
      <header className="bg-white shadow-lg border-b sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-4">
          <div className="flex justify-between items-center">
            <div className="flex items-center gap-4">
              <div className="text-3xl">🏭</div>
              <div>
                <h1 className="text-2xl font-bold text-gray-900">AI Meta Factory</h1>
                <p className="text-gray-600 text-sm">
                  Full-Stack AI Development Platform
                </p>
              </div>
            </div>

            <div className="flex items-center gap-4">
              {/* Git Connection */}
              <div className="flex items-center gap-2">
                {connectedGit ? (
                  <div className="flex items-center gap-2 px-3 py-1 bg-green-100 text-green-800 rounded-full">
                    <span>✅</span>
                    <span className="text-sm font-bold">GitHub Connected</span>
                  </div>
                ) : (
                  <button
                    onClick={connectGitHub}
                    disabled={isConfiguring}
                    className="flex items-center gap-2 px-4 py-2 bg-gray-900 text-white rounded-lg hover:bg-black disabled:opacity-50"
                  >
                    {isConfiguring ? 'Connecting...' : (
                      <>
                        <span>🔗</span>
                        <span className="font-bold">Connect GitHub</span>
                      </>
                    )}
                  </button>
                )}
              </div>
            </div>
          </div>

          {/* Main Navigation Tabs */}
          <div className="flex gap-1 mt-6 overflow-x-auto">
            {[
              { id: 'component', label: '🧠 AI Component Generator', icon: '🧠' },
              { id: 'fullstack', label: '🏭 Full-Stack Factory', icon: '🏭' },
              { id: 'canvas', label: '🎨 AI Canvas IDE', icon: '🎨' },
              { id: 'code', label: '💻 Code Editor', icon: '💻' },
              { id: 'export', label: '📦 Export & Deploy', icon: '📦' }
            ].map((tab) => (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as TabType)}
                className={`px-4 py-3 font-bold rounded-t-lg transition flex items-center gap-2 whitespace-nowrap ${
                  activeTab === tab.id
                    ? 'bg-white text-blue-600 border-t border-l border-r'
                    : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
                }`}
              >
                <span>{tab.icon}</span>
                <span className="hidden sm:inline">{tab.label}</span>
                <span className="sm:hidden">{tab.icon}</span>
              </button>
            ))}
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
        {/* Tech Stack Selector */}
        {(activeTab === 'component' || activeTab === 'fullstack' || activeTab === 'canvas') && (
          <div className="mb-8 p-4 sm:p-6 bg-white rounded-2xl shadow-lg border">
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 sm:gap-6">
              {/* Tech Stack */}
              <div>
                <h3 className="font-bold mb-3 flex items-center gap-2">
                  <span>⚙️</span>
                  <span className="hidden sm:inline">Tech Stack</span>
                  <span className="sm:hidden">Stack</span>
                </h3>
                <div className="flex flex-wrap gap-2">
                  {Object.entries(modeConfigs).map(([key, config]) => (
                    <button
                      key={key}
                      onClick={() => setMode(key as ModeType)}
                      className={`px-3 sm:px-4 py-2 sm:py-3 rounded-lg font-bold transition-all flex items-center gap-2 ${
                        mode === key
                          ? `bg-gradient-to-r ${config.color} text-white shadow-lg scale-105`
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      <span className="text-xl">{config.icon}</span>
                      <span className="hidden sm:inline">{config.name}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Database Selector */}
              <div>
                <h3 className="font-bold mb-3 flex items-center gap-2">
                  <span>🗄️</span>
                  <span className="hidden sm:inline">Database</span>
                  <span className="sm:hidden">DB</span>
                </h3>
                <div className="flex flex-wrap gap-2">
                  {Object.entries(databaseConfigs).map(([key, config]) => (
                    <button
                      key={key}
                      onClick={() => setDatabase(key)}
                      className={`px-3 py-2 rounded-lg font-bold transition-all flex items-center gap-2 ${
                        database === key
                          ? `bg-gradient-to-r ${config.color} text-white shadow-lg`
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      <span>{config.icon}</span>
                      <span className="hidden sm:inline">{config.name}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Git Provider */}
              <div>
                <h3 className="font-bold mb-3 flex items-center gap-2">
                  <span>🔗</span>
                  <span className="hidden sm:inline">Git Provider</span>
                  <span className="sm:hidden">Git</span>
                </h3>
                <div className="flex flex-wrap gap-2">
                  {Object.entries(gitConfigs).map(([key, config]) => (
                    <button
                      key={key}
                      onClick={() => setGitProvider(key)}
                      className={`px-3 py-2 rounded-lg font-bold transition-all flex items-center gap-2 ${
                        gitProvider === key
                          ? `bg-gradient-to-r ${config.color} text-white shadow-lg`
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                      }`}
                    >
                      <span>{config.icon}</span>
                      <span className="hidden sm:inline">{config.name}</span>
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Configuration Summary */}
            <div className="mt-6 p-4 bg-gradient-to-r from-blue-50 to-purple-50 rounded-xl border">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div className="flex flex-wrap items-center gap-2 sm:gap-4">
                  <div className={`px-3 sm:px-4 py-2 rounded-lg bg-gradient-to-r ${modeConfigs[mode].color} text-white font-bold text-sm sm:text-base`}>
                    {modeConfigs[mode].icon} {modeConfigs[mode].name}
                  </div>
                  <div className="text-gray-500 hidden sm:block">→</div>
                  <div className={`px-3 sm:px-4 py-2 rounded-lg bg-gradient-to-r ${databaseConfigs[database].color} text-white font-bold text-sm sm:text-base`}>
                    {databaseConfigs[database].icon} {databaseConfigs[database].name}
                  </div>
                  <div className="text-gray-500 hidden sm:block">→</div>
                  <div className={`px-3 sm:px-4 py-2 rounded-lg bg-gradient-to-r ${gitConfigs[gitProvider].color} text-white font-bold text-sm sm:text-base`}>
                    {gitConfigs[gitProvider].icon} {gitConfigs[gitProvider].name}
                  </div>
                </div>
                <div className="text-sm text-gray-600">
                  {connectedGit ? '✅ Ready to export' : '⚠️ Connect GitHub to export'}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Component Generator Tab */}
        {activeTab === 'component' && (
          <div className="space-y-8">
            <HonestAIPipeline />

            {/* Quick Actions */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="bg-white p-6 rounded-xl shadow text-center">
                <div className="text-2xl font-bold">{modeConfigs[mode].icon}</div>
                <div className="font-bold mt-2">{modeConfigs[mode].name}</div>
                <div className="text-sm text-gray-600">Tech Stack</div>
              </div>
              <div className="bg-white p-6 rounded-xl shadow text-center">
                <div className="text-2xl font-bold">{databaseConfigs[database].icon}</div>
                <div className="font-bold mt-2">{databaseConfigs[database].name}</div>
                <div className="text-sm text-gray-600">Database</div>
              </div>
              <div className="bg-white p-6 rounded-xl shadow text-center">
                <button
                  onClick={exportProject}
                  disabled={!connectedGit}
                  className="w-full py-3 bg-gradient-to-r from-green-600 to-blue-600 text-white font-bold rounded-lg hover:opacity-90 disabled:opacity-50"
                >
                  {connectedGit ? '🚀 Export Project' : '🔗 Connect GitHub First'}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Full-Stack Factory Tab */}
        {activeTab === 'fullstack' && (
          <div className="space-y-8">
            <FullStackFactory
              selectedStack={mode}
              selectedDatabase={database}
              selectedGitProvider={gitProvider}
              isGitConnected={connectedGit}
              onExport={exportProject}
            />
          </div>
        )}

        {/* Canvas Tab - Enhanced IDE */}
        {activeTab === 'canvas' && (
          <div className="min-h-[600px]">
            <EnhancedCanvasPanel
              initialFiles={{ ...baseFiles, ...generatedFiles }}
              onFilesChange={handleFilesChange}
              stack={getStackConfig()}
              projectName="ai-meta-factory-project"
              session={null}
            />
          </div>
        )}

        {/* Code Editor Tab (Simple version) */}
        {activeTab === 'code' && (
          <div className="bg-white rounded-2xl shadow-xl p-6 min-h-[500px]">
            <h2 className="text-2xl font-bold mb-6">💻 Code Editor</h2>
            <div className="border-2 border-gray-300 rounded-xl overflow-hidden">
              <div className="bg-gray-900 text-gray-300 px-4 py-2 flex justify-between">
                <div>generated-component.tsx</div>
                <button className="text-sm px-3 py-1 bg-blue-600 rounded">Copy</button>
              </div>
              <pre className="p-6 bg-gray-950 text-green-400 overflow-auto max-h-[400px]">
                {`// Generated AI Component
import React from 'react';

interface ComponentProps {
  title: string;
  theme?: 'light' | 'dark';
}

const AIGeneratedComponent: React.FC<ComponentProps> = ({
  title,
  theme = 'dark'
}) => {
  return (
    <div className={\`p-6 rounded-xl \${
      theme === 'dark'
        ? 'bg-gray-900 text-white'
        : 'bg-white text-gray-900'
    }\`}>
      <h1 className="text-2xl font-bold">{title}</h1>
      <p className="mt-3">
        This component was AI-generated with ${modeConfigs[mode].name}
        and ${databaseConfigs[database].name} configuration.
      </p>
    </div>
  );
};

export default AIGeneratedComponent;`}
              </pre>
            </div>
            <div className="mt-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
              <p className="text-blue-700 text-sm">
                💡 <strong>Note:</strong> For full IDE features including live preview, file explorer, and AI assistance,
                switch to the <button onClick={() => setActiveTab('canvas')} className="font-bold text-blue-600 underline">🎨 AI Canvas IDE</button> tab.
              </p>
            </div>
          </div>
        )}

        {/* Export & Deploy Tab */}
        {activeTab === 'export' && (
          <div className="bg-white rounded-2xl shadow-xl p-6">
            <h2 className="text-2xl font-bold mb-6">📦 Export & Deploy</h2>

            {/* Export Options */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 mb-8">
              <div className="border-2 border-gray-200 rounded-xl p-6 text-center hover:border-blue-500 hover:shadow-lg transition">
                <div className="text-4xl mb-4">📦</div>
                <h3 className="font-bold mb-2">Download ZIP</h3>
                <p className="text-sm text-gray-600 mb-4">Complete project files</p>
                <button className="px-4 py-2 bg-gray-900 text-white rounded-lg w-full">
                  Download
                </button>
              </div>

              <div className="border-2 border-gray-200 rounded-xl p-6 text-center hover:border-green-500 hover:shadow-lg transition">
                <div className="text-4xl mb-4">🚀</div>
                <h3 className="font-bold mb-2">Deploy to Vercel</h3>
                <p className="text-sm text-gray-600 mb-4">One-click deployment</p>
                <button className="px-4 py-2 bg-black text-white rounded-lg w-full">
                  Deploy Now
                </button>
              </div>

              <div className="border-2 border-gray-200 rounded-xl p-6 text-center hover:border-orange-500 hover:shadow-lg transition">
                <div className="text-4xl mb-4">🐙</div>
                <h3 className="font-bold mb-2">Push to GitHub</h3>
                <p className="text-sm text-gray-600 mb-4">Commit & push to repo</p>
                <button
                  onClick={exportProject}
                  disabled={!connectedGit}
                  className="px-4 py-2 bg-gray-800 text-white rounded-lg w-full disabled:opacity-50"
                >
                  {connectedGit ? 'Push to GitHub' : 'Connect GitHub First'}
                </button>
              </div>
            </div>

            {/* Project Configuration */}
            <div className="bg-gray-50 rounded-xl p-6">
              <h3 className="font-bold mb-4">Project Configuration</h3>
              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span>Tech Stack</span>
                  <span className="font-bold">{modeConfigs[mode].name}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span>Database</span>
                  <span className="font-bold">{databaseConfigs[database].name}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span>Git Provider</span>
                  <span className="font-bold">{gitConfigs[gitProvider].name}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span>Git Connection</span>
                  <span className={`font-bold ${connectedGit ? 'text-green-600' : 'text-red-600'}`}>
                    {connectedGit ? '✅ Connected' : '❌ Not Connected'}
                  </span>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
