"use client";

import { useState, useEffect } from 'react';
import {
  AlertCircle, CheckCircle, XCircle,
  RefreshCw, Play, Copy, Download,
  Sparkles, Cpu, Zap, Code as CodeIcon
} from 'lucide-react';

type HealthStatus = {
  system: {
    status: string;
    message: string;
  };
  openai: {
    configured: boolean;
    status: string;
  };
  gemini: {
    configured: boolean;
    keyFound: boolean;
    keySource: string;
    status: string;
  };
};

type PipelineStep = {
  id: number;
  name: string;
  model: string;
  status: 'waiting' | 'running' | 'success' | 'failed' | 'skipped' | 'not-configured';
  output?: string;
  time?: string;
};

// ADD THIS INTERFACE
interface HonestAIPipelineProps {
  onFilesGenerated?: (files: Record<string, string>) => void;
}

export default function HonestAIPipeline({ onFilesGenerated }: HonestAIPipelineProps) {
  const [prompt, setPrompt] = useState('A modern dark navigation bar with responsive design');
  const [health, setHealth] = useState<HealthStatus | null>(null);
  const [loadingHealth, setLoadingHealth] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState<any>(null);
  // ADD THIS STATE
  const [generatedFiles, setGeneratedFiles] = useState<Record<string, string>>({});
  const [steps, setSteps] = useState<PipelineStep[]>([]);
  const [showStructuredIdea, setShowStructuredIdea] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    checkHealth();
  }, []);

  useEffect(() => {
    if (health) {
      const hasOpenAI = health.openai.status.includes('✅');
      const hasGemini = health.gemini.status.includes('✅');

      if (hasGemini && hasOpenAI) {
        setSteps([
          { id: 1, name: 'Analysis', model: 'Gemini 1.5', status: 'waiting' },
          { id: 2, name: 'Structure', model: 'Gemini 1.5', status: 'waiting' },
          { id: 3, name: 'Code Gen', model: 'Gemini 1.5', status: 'waiting' },
          { id: 4, name: 'Review', model: 'GPT-4o', status: 'waiting' },
          { id: 5, name: 'Optimize', model: 'System', status: 'waiting' },
        ]);
      } else if (hasGemini) {
        setSteps([
          { id: 1, name: 'Analysis', model: 'Gemini 1.5', status: 'waiting' },
          { id: 2, name: 'Code Gen', model: 'Gemini 1.5', status: 'waiting' },
          { id: 3, name: 'Review', model: 'System', status: 'waiting' },
        ]);
      }
    }
  }, [health]);

  const checkHealth = async () => {
    setLoadingHealth(true);
    try {
      const response = await fetch('/api/health');
      const data = await response.json();
      setHealth(data);
    } catch (error) {
      console.error('Health check failed:', error);
    } finally {
      setLoadingHealth(false);
    }
  };

  const getStatusIcon = (status: string) => {
    if (status.includes('✅')) return <CheckCircle className="w-4 h-4 text-green-500" />;
    if (status.includes('❌')) return <XCircle className="w-4 h-4 text-red-500" />;
    if (status.includes('⚠️')) return <AlertCircle className="w-4 h-4 text-yellow-500" />;
    return null;
  };

  // ADD THIS FUNCTION TO CAPTURE FILES
  const captureGeneratedFiles = (componentCode: string) => {
    // Generate a filename from the prompt
    const fileName = prompt
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .substring(0, 30);
    
    const componentFileName = `components/${fileName || 'generated-component'}.tsx`;
    
    // Create a full component file
    const fullComponent = `// Generated by AI Meta Factory
// Prompt: "${prompt}"
// Timestamp: ${new Date().toISOString()}

${componentCode}

export default ${componentCode.includes('export default') ? '' : 'GeneratedComponent'};
`;
    
    const files = {
      [componentFileName]: fullComponent,
      // Add utility file
      'lib/ai-generated-utils.ts': `// AI Generated utilities
export const AI_GENERATED_COMPONENTS = {
  '${componentFileName}': {
    prompt: "${prompt}",
    generatedAt: "${new Date().toISOString()}",
    health: ${JSON.stringify(health, null, 2)}
  }
};

export function logGeneration() {
  console.log('AI Generated: ${componentFileName}');
}
`
    };
    
    setGeneratedFiles(files);
    
    // Call the callback if provided
    if (onFilesGenerated) {
      onFilesGenerated(files);
    }
    
    return files;
  };

  const generateComponent = async () => {
    if (!prompt.trim()) return;
    if (!health?.system.status.includes('🚀 READY')) return;

    setGenerating(true);
    setResult(null);
    setGeneratedFiles({});
    setSteps(prev => prev.map(step => ({ ...step, status: 'waiting' })));

    try {
      // Simulate step progression
      setSteps(prev => prev.map(step => 
        step.id === 1 ? { ...step, status: 'running' } : step
      ));

      // Call your AI generation API
      const response = await fetch('/api/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt,
          model: health.gemini.configured ? 'gemini' : 'gpt',
        }),
      });

      if (!response.ok) {
        throw new Error('Generation failed');
      }

      const data = await response.json();
      
      // Update steps
      setSteps(prev => prev.map(step => 
        step.id <= 3 ? { ...step, status: 'success', time: '1.2s' } : step
      ));
      
      // If there's a review step
      if (steps.length > 3) {
        setSteps(prev => prev.map(step => 
          step.id === 4 ? { ...step, status: 'running' } : step
        ));
        
        setTimeout(() => {
          setSteps(prev => prev.map(step => 
            step.id === 4 ? { ...step, status: 'success', time: '0.8s' } : step
          ));
          
          // Capture the generated files
          if (data.code) {
            const files = captureGeneratedFiles(data.code);
            setResult({
              code: data.code,
              files: files,
              timestamp: new Date().toISOString()
            });
          } else {
            setResult(data);
          }
          
          setGenerating(false);
        }, 800);
      } else {
        // Capture the generated files
        if (data.code) {
          const files = captureGeneratedFiles(data.code);
          setResult({
            code: data.code,
            files: files,
            timestamp: new Date().toISOString()
          });
        } else {
          setResult(data);
        }
        
        setGenerating(false);
      }

    } catch (error) {
      console.error('Generation error:', error);
      setSteps(prev => prev.map(step => 
        step.status === 'running' ? { ...step, status: 'failed' } : step
      ));
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Health Status */}
      <div className="bg-white rounded-2xl border shadow-sm p-6">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-xl font-bold text-gray-900">⚡ Honest AI Pipeline</h2>
            <p className="text-gray-600">Multi-model AI pipeline with transparent health checks</p>
          </div>
          <button
            onClick={checkHealth}
            disabled={loadingHealth}
            className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg text-sm font-medium hover:bg-gray-200 disabled:opacity-50 flex items-center gap-2"
          >
            <RefreshCw className={`w-4 h-4 ${loadingHealth ? 'animate-spin' : ''}`} />
            {loadingHealth ? 'Checking...' : 'Refresh Health'}
          </button>
        </div>

        {loadingHealth ? (
          <div className="flex items-center justify-center py-8">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
          </div>
        ) : health ? (
          <div className="space-y-4">
            <div className="p-4 bg-gradient-to-r from-green-50 to-emerald-50 rounded-xl border border-green-200">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-green-100 rounded-lg flex items-center justify-center">
                    <Sparkles className="w-5 h-5 text-green-600" />
                  </div>
                  <div>
                    <div className="font-bold text-gray-900">{health.system.status}</div>
                    <div className="text-sm text-gray-600">{health.system.message}</div>
                  </div>
                </div>
                <div className="text-sm text-gray-500">
                  {health.gemini.configured ? 'Gemini ✅' : 'Gemini ❌'} • {health.openai.configured ? 'OpenAI ✅' : 'OpenAI ❌'}
                </div>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="p-4 bg-white border rounded-xl">
                <div className="flex items-center justify-between mb-2">
                  <div className="font-medium text-gray-900">Gemini 1.5</div>
                  {getStatusIcon(health.gemini.status)}
                </div>
                <div className="text-sm text-gray-600">
                  {health.gemini.keyFound ? `Key: ${health.gemini.keySource}` : 'No API key'}
                </div>
              </div>
              <div className="p-4 bg-white border rounded-xl">
                <div className="flex items-center justify-between mb-2">
                  <div className="font-medium text-gray-900">GPT-4o</div>
                  {getStatusIcon(health.openai.status)}
                </div>
                <div className="text-sm text-gray-600">
                  {health.openai.configured ? 'Configured' : 'Not configured'}
                </div>
              </div>
            </div>
          </div>
        ) : (
          <div className="text-center py-8 text-gray-500">
            Failed to load health status
          </div>
        )}
      </div>

      {/* Pipeline Steps */}
      <div className="bg-white rounded-2xl border shadow-sm p-6">
        <h3 className="font-bold text-lg text-gray-900 mb-6">Pipeline Steps</h3>
        <div className="space-y-4">
          {steps.map((step) => (
            <div key={step.id} className="flex items-center justify-between p-4 border rounded-xl">
              <div className="flex items-center gap-4">
                <div className={`w-8 h-8 rounded-full flex items-center justify-center ${
                  step.status === 'waiting' ? 'bg-gray-100' :
                  step.status === 'running' ? 'bg-blue-100 animate-pulse' :
                  step.status === 'success' ? 'bg-green-100' :
                  step.status === 'failed' ? 'bg-red-100' : 'bg-gray-100'
                }`}>
                  {step.status === 'waiting' && <div className="w-4 h-4 bg-gray-300 rounded-full"></div>}
                  {step.status === 'running' && <div className="w-4 h-4 bg-blue-600 rounded-full"></div>}
                  {step.status === 'success' && <CheckCircle className="w-4 h-4 text-green-600" />}
                  {step.status === 'failed' && <XCircle className="w-4 h-4 text-red-600" />}
                </div>
                <div>
                  <div className="font-medium text-gray-900">{step.name}</div>
                  <div className="text-sm text-gray-500">{step.model}</div>
                </div>
              </div>
              <div className="text-sm text-gray-500">
                {step.time && <span className="font-mono">{step.time}</span>}
                {!step.time && step.status === 'waiting' && 'Pending'}
                {!step.time && step.status === 'running' && 'Running...'}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Prompt Input */}
      <div className="bg-white rounded-2xl border shadow-sm p-6">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h3 className="font-bold text-lg text-gray-900">Component Prompt</h3>
            <p className="text-gray-600">Describe the component you want to generate</p>
          </div>
          <button
            onClick={() => setShowStructuredIdea(!showStructuredIdea)}
            className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg text-sm font-medium hover:bg-gray-200"
          >
            {showStructuredIdea ? 'Simple Prompt' : 'Structured Idea'}
          </button>
        </div>

        {showStructuredIdea ? (
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Component Type</label>
                <select className="w-full px-4 py-3 border rounded-lg bg-gray-50">
                  <option>Navigation</option>
                  <option>Button</option>
                  <option>Card</option>
                  <option>Form</option>
                  <option>Modal</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Style</label>
                <select className="w-full px-4 py-3 border rounded-lg bg-gray-50">
                  <option>Modern</option>
                  <option>Minimal</option>
                  <option>Dark</option>
                  <option>Glassmorphism</option>
                </select>
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Additional Details</label>
              <textarea
                className="w-full px-4 py-3 border rounded-lg bg-gray-50 h-32"
                placeholder="Any specific requirements or functionality..."
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
              />
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <textarea
              className="w-full px-4 py-3 border rounded-lg bg-gray-50 h-32"
              placeholder="Describe your component... e.g., 'A modern dark navigation bar with responsive design'"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
            />
            <div className="flex items-center text-sm text-gray-600">
              <Sparkles className="w-4 h-4 mr-2" />
              Be specific for better results. Include style, functionality, and any constraints.
            </div>
          </div>
        )}

        <div className="mt-6">
          <button
            onClick={generateComponent}
            disabled={generating || !health?.system.status.includes('🚀 READY')}
            className="w-full py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-bold rounded-xl hover:opacity-90 disabled:opacity-50 transition-opacity flex items-center justify-center gap-3"
          >
            {generating ? (
              <>
                <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                Generating...
              </>
            ) : (
              <>
                <Play className="w-5 h-5" />
                Generate Component
              </>
            )}
          </button>
        </div>
      </div>

      {/* Results */}
      {result && (
        <div className="bg-white rounded-2xl border shadow-sm p-6">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h3 className="font-bold text-lg text-gray-900">Generated Component</h3>
              <p className="text-gray-600">AI-generated React/Next.js component</p>
            </div>
            <div className="flex gap-2">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(result.code || JSON.stringify(result, null, 2));
                  setCopied(true);
                  setTimeout(() => setCopied(false), 2000);
                }}
                className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg text-sm font-medium hover:bg-gray-200 flex items-center gap-2"
              >
                <Copy className="w-4 h-4" />
                {copied ? 'Copied!' : 'Copy'}
              </button>
              <button className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 flex items-center gap-2">
                <Download className="w-4 h-4" />
                Download
              </button>
            </div>
          </div>

          <div className="border rounded-xl overflow-hidden">
            <div className="bg-gray-900 text-gray-300 px-4 py-3 flex justify-between items-center">
              <div className="flex items-center gap-2">
                <CodeIcon className="w-4 h-4" />
                <span className="font-mono text-sm">generated-component.tsx</span>
              </div>
              <div className="text-xs text-gray-400">AI Generated</div>
            </div>
            <pre className="p-6 bg-gray-950 text-gray-100 overflow-auto max-h-[500px] text-sm">
              {result.code || JSON.stringify(result, null, 2)}
            </pre>
          </div>
          
          {/* ADD THIS SECTION TO SHOW GENERATED FILES */}
          {result.files && (
            <div className="mt-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <div className="font-medium text-gray-900">Generated Files</div>
                  <div className="text-sm text-gray-600">
                    {Object.keys(result.files).length} files created
                  </div>
                </div>
                <div className="text-sm text-gray-500">
                  Ready for Canvas Diff View
                </div>
              </div>
              <div className="space-y-2">
                {Object.entries(result.files).map(([fileName]) => (
                  <div key={fileName} className="px-3 py-2 bg-white rounded border text-sm flex justify-between">
                    <div className="font-mono">{fileName}</div>
                    <div className="text-gray-500">
                      {result.files[fileName].split('\n').length} lines
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
