"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

interface HonestAIPipelineProps {
  onFilesGenerated?: (files: Record<string, string>) => void;
}

export default function HonestAIPipeline({ onFilesGenerated }: HonestAIPipelineProps) {
  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<string>("");

  const handleGenerate = async () => {
    if (!prompt) return;
    setLoading(true);

    try {
      // Mock AI generation
      await new Promise((resolve) => setTimeout(resolve, 1500));
      
      const mockFiles = {
        'components/GeneratedComponent.tsx': `import React from 'react';

interface GeneratedComponentProps {
  title: string;
  description?: string;
}

export default function GeneratedComponent({ 
  title, 
  description = "AI-generated component" 
}: GeneratedComponentProps) {
  return (
    <div className="bg-white rounded-xl shadow-lg border p-6">
      <h2 className="text-2xl font-bold text-gray-900 mb-3">{title}</h2>
      <p className="text-gray-600 mb-6">{description}</p>
      <div className="flex gap-3">
        <button className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
          Primary Action
        </button>
        <button className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
          Secondary
        </button>
      </div>
      <div className="mt-6 text-sm text-gray-500">
        Generated from prompt: "${prompt}"
      </div>
    </div>
  );
}`,
        'components/GeneratedComponent.stories.tsx': `import type { Meta, StoryObj } from '@storybook/react';
import GeneratedComponent from './GeneratedComponent';

const meta: Meta<typeof GeneratedComponent> = {
  title: 'Components/AIGenerated/GeneratedComponent',
  component: GeneratedComponent,
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof GeneratedComponent>;

export const Default: Story = {
  args: {
    title: 'AI Generated Component',
    description: 'This component was generated by AI based on your description',
  },
};`,
        'components/GeneratedComponent.test.tsx': `import { render, screen } from '@testing-library/react';
import GeneratedComponent from './GeneratedComponent';

describe('GeneratedComponent', () => {
  it('renders the title correctly', () => {
    render(<GeneratedComponent title="Test Title" />);
    expect(screen.getByText('Test Title')).toBeInTheDocument();
  });

  it('renders the default description when none provided', () => {
    render(<GeneratedComponent title="Test" />);
    expect(screen.getByText('AI-generated component')).toBeInTheDocument();
  });
});`,
        'README.md': `# Generated Component

This component was generated by AI Meta Factory.

## Prompt
${prompt}

## Files
- components/GeneratedComponent.tsx
- components/GeneratedComponent.stories.tsx  
- components/GeneratedComponent.test.tsx

## Features
- TypeScript
- Storybook stories
- Unit tests
- Responsive design
- Best practices
`
      };
      
      setResult(`✅ Successfully generated 4 files from your prompt: "${prompt}"`);
      
      if (onFilesGenerated) {
        onFilesGenerated(mockFiles);
      }
    } catch (err) {
      setResult("❌ Error generating output. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white rounded-xl border shadow-sm p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">🎯 Honest AI Pipeline</h2>
          <p className="text-gray-600 mt-1">Describe what you want to build, AI will generate the code</p>
        </div>
        <div className="px-3 py-1 bg-gradient-to-r from-blue-600 to-purple-600 text-white text-sm font-medium rounded-full">
          Real AI
        </div>
      </div>
      
      <div className="space-y-6">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Component Description
          </label>
          <textarea
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder="Enter your prompt... (e.g., Create a responsive navbar with dark mode toggle)"
            className="w-full h-40 p-4 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 resize-none"
          />
          <div className="mt-2 text-sm text-gray-500">
            Be specific about features, styling, and behavior for better results.
          </div>
        </div>
        
        <Button
          onClick={handleGenerate}
          disabled={loading || !prompt.trim()}
          className="w-full py-3"
        >
          {loading ? (
            <span className="flex items-center justify-center gap-2">
              <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
              Generating with AI...
            </span>
          ) : (
            "🚀 Generate Component"
          )}
        </Button>
        
        {result && (
          <div className="mt-4 p-4 bg-green-50 border border-green-200 rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
              <strong className="text-green-800">Result:</strong>
            </div>
            <p className="text-green-700 whitespace-pre-wrap">{result}</p>
            
            <div className="mt-4 grid grid-cols-4 gap-2">
              <div className="text-center p-2 bg-white rounded border">
                <div className="text-xs text-gray-500">Files</div>
                <div className="font-bold">4</div>
              </div>
              <div className="text-center p-2 bg-white rounded border">
                <div className="text-xs text-gray-500">Lines</div>
                <div className="font-bold">~120</div>
              </div>
              <div className="text-center p-2 bg-white rounded border">
                <div className="text-xs text-gray-500">TypeScript</div>
                <div className="font-bold">✅</div>
              </div>
              <div className="text-center p-2 bg-white rounded border">
                <div className="text-xs text-gray-500">Tests</div>
                <div className="font-bold">✅</div>
              </div>
            </div>
          </div>
        )}
        
        <div className="pt-4 border-t border-gray-200">
          <h3 className="font-medium text-gray-900 mb-3">AI Pipeline Features</h3>
          <div className="grid grid-cols-2 gap-3">
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <span className="text-sm">Real-time generation</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <span className="text-sm">Production-ready code</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <span className="text-sm">TypeScript & tests</span>
            </div>
            <div className="flex items-center gap-2">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <span className="text-sm">Best practices</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
