FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci --only=production

COPY lib/socket lib/socket
COPY server/socket.js .

ENV NODE_ENV production
ENV PORT 3001

EXPOSE 3001

CMD ["node", "socket.js"]
