import { Template } from '../TemplateLibrary';

export const landingPageTemplate: Template = {
  id: 'landing-page-basic',
  name: 'Basic Landing Page',
  description: 'A simple landing page with hero section, features, and footer.',
  category: 'website',
  thumbnail: '/templates/landing-page-thumb.jpg',
  stack: ['HTML', 'CSS', 'JavaScript'],
  files: {
    'index.html': `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>My Landing Page</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header class="hero">
    <h1>Welcome to My Site</h1>
    <p>This is a simple landing page generated by AI Meta Factory.</p>
    <button class="cta">Get Started</button>
  </header>
  <section class="features">
    <div class="feature">
      <h3>Feature 1</h3>
      <p>Description of feature 1.</p>
    </div>
    <div class="feature">
      <h3>Feature 2</h3>
      <p>Description of feature 2.</p>
    </div>
    <div class="feature">
      <h3>Feature 3</h3>
      <p>Description of feature 3.</p>
    </div>
  </section>
  <footer>
    <p>&copy; 2025 My Company</p>
  </footer>
  <script src="script.js"></script>
</body>
</html>`,
    'style.css': `body {
  margin: 0;
  font-family: Arial, sans-serif;
}
.hero {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  text-align: center;
  padding: 100px 20px;
}
.hero h1 {
  font-size: 3rem;
  margin-bottom: 20px;
}
.hero p {
  font-size: 1.2rem;
  margin-bottom: 30px;
}
.cta {
  background: white;
  color: #667eea;
  border: none;
  padding: 12px 30px;
  font-size: 1rem;
  border-radius: 5px;
  cursor: pointer;
}
.features {
  display: flex;
  justify-content: center;
  gap: 40px;
  padding: 60px 20px;
}
.feature {
  text-align: center;
  max-width: 300px;
}
footer {
  background: #333;
  color: white;
  text-align: center;
  padding: 20px;
}`,
    'script.js': `console.log('Landing page loaded');`,
  },
};
