import JSZip from 'jszip';
import { saveAs } from 'file-saver';

interface ExportOptions {
  projectName: string;
  stack: string;
  database: string;
  files: Record<string, string>;
  description?: string;
  version?: string;
}

export class EnhancedProjectExporter {
  async exportAsZip(options: ExportOptions): Promise<void> {
    const zip = new JSZip();
    const { projectName, files } = options;

    // Add all files
    Object.entries(files).forEach(([filePath, content]) => {
      zip.file(filePath, content);
    });

    // Add package.json
    zip.file('package.json', JSON.stringify(this.generatePackageJson(options), null, 2));

    // Add configuration files based on stack
    await this.addConfigFiles(zip, options);

    // Add README
    zip.file('README.md', this.generateReadme(options));

    // Generate and download
    const content = await zip.generateAsync({ type: 'blob' });
    saveAs(content, `${projectName}.zip`);
  }

  private generatePackageJson(options: ExportOptions): any {
    const base = {
      name: options.projectName,
      version: options.version || '1.0.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint'
      },
      dependencies: {
        next: '^14.0.0',
        react: '^18.2.0',
        'react-dom': '^18.2.0',
        ...(options.stack.includes('typescript') && { typescript: '^5.0.0' }),
        ...(options.database === 'supabase' && { '@supabase/supabase-js': '^2.0.0' }),
        ...(options.database === 'firebase' && { firebase: '^10.0.0' }),
        ...(options.database === 'mongodb' && { mongodb: '^6.0.0', mongoose: '^7.0.0' }),
      },
      devDependencies: {
        '@types/node': '^20.0.0',
        '@types/react': '^18.2.0',
        '@types/react-dom': '^18.2.0',
        'eslint': '^8.0.0',
        'eslint-config-next': '14.0.0',
      }
    };

    return base;
  }

  private async addConfigFiles(zip: JSZip, options: ExportOptions): Promise<void> {
    if (options.stack.includes('nextjs') || options.stack.includes('typescript')) {
      zip.file('tsconfig.json', JSON.stringify({
        compilerOptions: {
          target: "es5",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          paths: {
            "@/*": ["./*"]
          }
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
        exclude: ["node_modules"]
      }, null, 2));

      zip.file('next.config.js', `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

module.exports = nextConfig;`);
    }

    if (options.stack.includes('tailwind')) {
      zip.file('tailwind.config.js', `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`);
    }
  }

  private generateReadme(options: ExportOptions): string {
    return `# ${options.projectName}

${options.description || 'Generated by AI Meta Factory'}

## 🚀 Getting Started

First, install dependencies:

\`\`\`bash
npm install
\`\`\`

Then run the development server:

\`\`\`bash
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) in your browser.

## 📁 Project Structure

This project uses:
- **Stack**: ${options.stack}
- **Database**: ${options.database}
- **Total Files**: ${Object.keys(options.files).length}

## 🛠️ Built With

- [Next.js](https://nextjs.org/)
- [React](https://reactjs.org/)
- [TypeScript](https://www.typescriptlang.org/)
- [Tailwind CSS](https://tailwindcss.com/)

## 📄 License

This project is licensed under the MIT License.

---

**Generated by AI Meta Factory** • ${new Date().toLocaleDateString()}
`;
  }
}
