import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export interface ProjectFile {
  name: string;
  content: string;
  path: string;
}

export interface ExportConfig {
  projectName: string;
  stack: string;
  database: string;
  gitProvider: string;
  files: ProjectFile[];
}

export class ProjectExporter {
  static async exportAsZip(config: ExportConfig): Promise<void> {
    const zip = new JSZip();
    
    // Create project structure
    const projectFolder = zip.folder(config.projectName);
    
    if (!projectFolder) {
      throw new Error('Failed to create project folder in ZIP');
    }
    
    // Add all files
    config.files.forEach(file => {
      projectFolder.file(file.path, file.content);
    });
    
    // Add README.md
    projectFolder.file('README.md', this.generateReadme(config));
    
    // Add .gitignore
    projectFolder.file('.gitignore', this.generateGitignore(config));
    
    // Add .env.example
    projectFolder.file('.env.example', this.generateEnvExample(config));
    
    // Generate and download ZIP
    const content = await zip.generateAsync({ type: 'blob' });
    saveAs(content, `${config.projectName}.zip`);
  }
  
  static generateReadme(config: ExportConfig): string {
    return `# ${config.projectName}

## 🚀 AI-Generated Project

This project was generated using AI Meta Factory with the following configuration:

- **Stack**: ${config.stack}
- **Database**: ${config.database}
- **Git Provider**: ${config.gitProvider}
- **Generated At**: ${new Date().toISOString()}

## 📦 Installation

\`\`\`bash
# Install dependencies
npm install

# Set up environment variables
cp .env.example .env.local
# Edit .env.local with your values

# Run development server
npm run dev
\`\`\`

## 🗄️ Database Setup

${this.getDatabaseSetupInstructions(config.database)}

## 🌐 Deployment

${this.getDeploymentInstructions(config.stack)}

## 🤖 Generated by AI Meta Factory

This project was automatically generated. Review and customize the code as needed.
`;
  }
  
  static generateGitignore(config: ExportConfig): string {
    const baseIgnore = `# Dependencies
node_modules/
.next/
dist/
build/

# Environment variables
.env.local
.env.development.local
.env.test.local
.env.production.local

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db

# Logs
*.log
`;
    
    if (config.stack.includes('next')) {
      return baseIgnore + '\n# Next.js\n.next/\n';
    }
    
    if (config.stack.includes('flutter')) {
      return baseIgnore + '\n# Flutter\n.dart_tool/\n.packages\n.pub-cache/\n';
    }
    
    return baseIgnore;
  }
  
  static generateEnvExample(config: ExportConfig): string {
    const envVars: Record<string, string[]> = {
      supabase: [
        'SUPABASE_URL=',
        'SUPABASE_ANON_KEY=',
        'SUPABASE_SERVICE_ROLE_KEY='
      ],
      firebase: [
        'FIREBASE_API_KEY=',
        'FIREBASE_AUTH_DOMAIN=',
        'FIREBASE_PROJECT_ID=',
        'FIREBASE_STORAGE_BUCKET=',
        'FIREBASE_MESSAGING_SENDER_ID=',
        'FIREBASE_APP_ID='
      ],
      mongodb: [
        'MONGODB_URI=',
        'MONGODB_DB_NAME='
      ],
      planetscale: [
        'DATABASE_URL='
      ]
    };
    
    const dbVars = envVars[config.database] || [];
    const stackVars = config.stack === 'nextjs' ? [
      'NEXT_PUBLIC_APP_URL=http://localhost:3000',
      'NEXT_PUBLIC_API_URL=http://localhost:3000/api'
    ] : [];
    
    return [...stackVars, ...dbVars, ''].join('\n');
  }
  
  static getDatabaseSetupInstructions(database: string): string {
    const instructions: Record<string, string> = {
      supabase: `1. Create a Supabase project at https://supabase.com
2. Get your project URL and anon key from Settings > API
3. Add them to your .env.local file
4. Run the SQL migrations from the generated schema file`,
      firebase: `1. Create a Firebase project at https://console.firebase.google.com
2. Add a web app to your project
3. Get your Firebase configuration from Project Settings
4. Add the configuration to your .env.local file`,
      mongodb: `1. Create a MongoDB Atlas cluster at https://cloud.mongodb.com
2. Get your connection string from Connect > Connect your application
3. Add the connection string to your .env.local file`,
      planetscale: `1. Create a PlanetScale database at https://planetscale.com
2. Get your connection string from Connect > Connect with Prisma/Node.js
3. Add the connection string to your .env.local file`,
      none: 'No database setup required for this project.'
    };
    
    return instructions[database] || 'Database setup instructions not available.';
  }
  
  static getDeploymentInstructions(stack: string): string {
    const instructions: Record<string, string> = {
      nextjs: `### Vercel (Recommended)
1. Push your code to GitHub
2. Import project in Vercel (https://vercel.com)
3. Add environment variables
4. Deploy!

### Netlify
1. Push your code to GitHub
2. Import project in Netlify (https://netlify.com)
3. Add environment variables
4. Deploy!`,
      react: `### Vercel
1. Push your code to GitHub
2. Import project in Vercel
3. Set build command: \`npm run build\`
4. Deploy!

### Netlify
1. Push your code to GitHub
2. Import project in Netlify
3. Set build command: \`npm run build\`
4. Deploy!`,
      flutter: `### Firebase Hosting
1. Install Flutter and build web version
2. Deploy to Firebase Hosting:
   \`\`\`bash
   flutter build web
   firebase deploy --only hosting
   \`\`\``,
      node: `### Railway / Render
1. Push your code to GitHub
2. Create new service on Railway/Render
3. Add environment variables
4. Deploy!`,
      python: `### Railway / Render
1. Push your code to GitHub
2. Create new service on Railway/Render
3. Add environment variables
4. Deploy!`
    };
    
    return instructions[stack] || 'Deployment instructions not available for this stack.';
  }
  
  static createExportConfig(projectData: any, config: {
    stack: string;
    database: string;
    gitProvider: string;
  }): ExportConfig {
    const files: ProjectFile[] = [];
    
    // Add generated files from AI
    if (projectData.files && typeof projectData.files === 'object') {
      Object.entries(projectData.files).forEach(([path, content]) => {
        files.push({
          name: path.split('/').pop() || 'file',
          content: String(content),
          path
        });
      });
    }
    
    // Add essential files if not present
    const essentialFiles = [
      { path: 'package.json', content: JSON.stringify({
        name: projectData.name || 'ai-project',
        version: '1.0.0',
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start'
        },
        dependencies: {},
        devDependencies: {}
      }, null, 2) },
      { path: 'src/index.ts', content: '// Main entry point\nconsole.log("Hello from AI Meta Factory!");' }
    ];
    
    essentialFiles.forEach(file => {
      if (!files.some(f => f.path === file.path)) {
        files.push({
          name: file.path.split('/').pop() || 'file',
          content: file.content,
          path: file.path
        });
      }
    });
    
    return {
      projectName: projectData.name || 'ai-meta-factory-project',
      stack: config.stack,
      database: config.database,
      gitProvider: config.gitProvider,
      files
    };
  }
}
