import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export interface ProjectFile {
  name: string;
  content: string;
  path: string;
  type: 'file' | 'directory';
}

export interface ExportConfig {
  projectName: string;
  stack: string;
  database: string;
  gitProvider: string;
  files: Record<string, string>;
}

export class ProjectExporter {
  static async exportAsZip(config: ExportConfig): Promise<boolean> {
    try {
      const zip = new JSZip();
      
      // Create project folder structure
      const projectFolder = zip.folder(config.projectName);
      
      if (!projectFolder) {
        throw new Error('Failed to create project folder in ZIP');
      }
      
      // Add all files to ZIP
      Object.entries(config.files).forEach(([filePath, content]) => {
        projectFolder.file(filePath, content);
      });
      
      // Add essential configuration files
      projectFolder.file('README.md', this.generateReadme(config));
      projectFolder.file('.gitignore', this.generateGitignore(config));
      projectFolder.file('.env.example', this.generateEnvExample(config));
      projectFolder.file('package.json', this.generatePackageJson(config));
      projectFolder.file('tsconfig.json', this.generateTsConfig(config));
      
      // Generate ZIP file
      const content = await zip.generateAsync({ 
        type: 'blob',
        compression: 'DEFLATE',
        compressionOptions: {
          level: 9
        }
      });
      
      // Download the ZIP
      saveAs(content, `${config.projectName}-${Date.now()}.zip`);
      
      return true;
    } catch (error) {
      console.error('Export failed:', error);
      return false;
    }
  }
  
  static generateReadme(config: ExportConfig): string {
    return `# ${config.projectName}

## 🚀 AI-Generated Project

This project was generated using **AI Meta Factory** with the following configuration:

- **Tech Stack**: ${config.stack}
- **Database**: ${config.database}
- **Git Provider**: ${config.gitProvider}
- **Generated At**: ${new Date().toISOString()}
- **Files Generated**: ${Object.keys(config.files).length}

## 📦 Installation

\`\`\`bash
# Install dependencies
npm install

# Set up environment variables
cp .env.example .env.local

# Run development server
npm run dev
\`\`\`

## 🗄️ Database Setup

${this.getDatabaseSetupInstructions(config.database)}

## 🌐 Deployment

${this.getDeploymentInstructions(config.stack)}

## 🤖 Generated by AI Meta Factory

This project was automatically generated. Review and customize the code as needed.

## 📁 Project Structure

\`\`\`
${Object.keys(config.files).join('\n')}
\`\`\`
`;
  }
  
  static generateGitignore(config: ExportConfig): string {
    const base = `# Dependencies
node_modules/
.next/
dist/
build/
out/

# Environment variables
.env.local
.env.development.local
.env.test.local
.env.production.local

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
`;

    if (config.stack.includes('next')) {
      return base + '\n# Next.js\n.next/\n';
    }
    
    if (config.stack.includes('react')) {
      return base + '\n# React\nbuild/\n';
    }
    
    return base;
  }
  
  static generateEnvExample(config: ExportConfig): string {
    const envVars: Record<string, string[]> = {
      supabase: [
        'NEXT_PUBLIC_SUPABASE_URL=',
        'NEXT_PUBLIC_SUPABASE_ANON_KEY=',
        'SUPABASE_SERVICE_ROLE_KEY='
      ],
      firebase: [
        'NEXT_PUBLIC_FIREBASE_API_KEY=',
        'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=',
        'NEXT_PUBLIC_FIREBASE_PROJECT_ID=',
        'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=',
        'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=',
        'NEXT_PUBLIC_FIREBASE_APP_ID='
      ],
      mongodb: [
        'MONGODB_URI=',
        'MONGODB_DB_NAME='
      ],
      planetscale: [
        'DATABASE_URL='
      ]
    };
    
    const dbVars = envVars[config.database] || [];
    const stackVars = config.stack === 'nextjs' ? [
      'NEXT_PUBLIC_APP_URL=http://localhost:3000',
      'NEXT_PUBLIC_API_URL=http://localhost:3000/api'
    ] : [];
    
    return [...stackVars, ...dbVars, ''].join('\n');
  }
  
  static generatePackageJson(config: ExportConfig): string {
    const basePackage = {
      name: config.projectName.toLowerCase().replace(/\s+/g, '-'),
      version: '1.0.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint'
      },
      dependencies: {
        next: '^14.0.0',
        react: '^18.2.0',
        'react-dom': '^18.2.0'
      },
      devDependencies: {
        '@types/node': '^20.0.0',
        '@types/react': '^18.2.0',
        '@types/react-dom': '^18.2.0',
        typescript: '^5.0.0',
        tailwindcss: '^3.3.0',
        autoprefixer: '^10.0.0',
        postcss: '^8.0.0'
      }
    };
    
    return JSON.stringify(basePackage, null, 2);
  }
  
  static generateTsConfig(config: ExportConfig): string {
    return JSON.stringify({
      compilerOptions: {
        target: 'es5',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./*'] }
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules']
    }, null, 2);
  }
  
  static getDatabaseSetupInstructions(database: string): string {
    const instructions: Record<string, string> = {
      supabase: `1. Create a Supabase project at https://supabase.com
2. Get your project URL and anon key from Settings > API
3. Add them to your .env.local file
4. Run the SQL migrations from the generated schema file`,
      firebase: `1. Create a Firebase project at https://console.firebase.google.com
2. Add a web app to your project
3. Get your Firebase configuration from Project Settings
4. Add the configuration to your .env.local file`,
      mongodb: `1. Create a MongoDB Atlas cluster at https://cloud.mongodb.com
2. Get your connection string from Connect > Connect your application
3. Add the connection string to your .env.local file`,
      planetscale: `1. Create a PlanetScale database at https://planetscale.com
2. Get your connection string from Connect > Connect with Prisma/Node.js
3. Add the connection string to your .env.local file`,
      none: 'No database setup required for this project.'
    };
    
    return instructions[database] || 'Database setup instructions not available.';
  }
  
  static getDeploymentInstructions(stack: string): string {
    const instructions: Record<string, string> = {
      nextjs: `### Vercel (Recommended)
1. Push your code to GitHub
2. Import project in Vercel (https://vercel.com)
3. Add environment variables
4. Deploy!

### Netlify
1. Push your code to GitHub
2. Import project in Netlify (https://netlify.com)
3. Add environment variables
4. Deploy!`,
      react: `### Vercel
1. Push your code to GitHub
2. Import project in Vercel
3. Set build command: \`npm run build\`
4. Deploy!

### Netlify
1. Push your code to GitHub
2. Import project in Netlify
3. Set build command: \`npm run build\`
4. Deploy!`,
      flutter: `### Firebase Hosting
1. Install Flutter and build web version
2. Deploy to Firebase Hosting:
   \`\`\`bash
   flutter build web
   firebase deploy --only hosting
   \`\`\``,
      node: `### Railway / Render
1. Push your code to GitHub
2. Create new service on Railway/Render
3. Add environment variables
4. Deploy!`,
      python: `### Railway / Render
1. Push your code to GitHub
2. Create new service on Railway/Render
3. Add environment variables
4. Deploy!`
    };
    
    return instructions[stack] || 'Deployment instructions not available for this stack.';
  }
}
