import JSZip from 'jszip';
import { saveAs } from 'file-saver';

/**
 * Export files as a ZIP download
 */
export async function exportAsZip(files: Record<string, string>, projectName: string = 'ai-project') {
  try {
    const zip = new JSZip();
    
    // Add each file to the ZIP
    Object.entries(files).forEach(([path, content]) => {
      zip.file(path, content);
    });
    
    // Add README with project info
    const readmeContent = `# AI Generated Project
    
This project was generated by AI Meta Factory.
    
## Files:
${Object.keys(files).map(file => `- ${file}`).join('\n')}
    
## Generated At:
${new Date().toISOString()}
    
--- 
Happy coding! 🚀`;
    
    zip.file('README.md', readmeContent);
    
    // Generate ZIP file
    const blob = await zip.generateAsync({ type: 'blob' });
    
    // Download the ZIP
    saveAs(blob, `${projectName}-${Date.now()}.zip`);
    
    return true;
  } catch (error) {
    console.error('Failed to export ZIP:', error);
    return false;
  }
}

/**
 * Get file statistics
 */
export function getFileStats(files: Record<string, string>) {
  const fileCount = Object.keys(files).length;
  const lineCount = Object.values(files)
    .reduce((sum, content) => sum + content.split('\n').length, 0);
  const charCount = Object.values(files)
    .reduce((sum, content) => sum + content.length, 0);
  
  const extensions = Object.keys(files).reduce((acc, filename) => {
    const ext = filename.split('.').pop()?.toLowerCase() || 'unknown';
    acc[ext] = (acc[ext] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);
  
  const mostCommonExt = Object.entries(extensions)
    .sort(([, a], [, b]) => b - a)[0]?.[0] || 'none';
  
  return {
    fileCount,
    lineCount,
    charCount,
    extensions,
    mostCommonExt
  };
}

/**
 * Format file size
 */
export function formatFileSize(bytes: number): string {
  if (bytes === 0) return '0 Bytes';
  
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

/**
 * Validate file structure
 */
export function validateFiles(files: Record<string, string>): {
  isValid: boolean;
  errors: string[];
} {
  const errors: string[] = [];
  
  // Check for empty files
  Object.entries(files).forEach(([path, content]) => {
    if (!content.trim()) {
      errors.push(`File "${path}" is empty`);
    }
  });
  
  // Check for duplicate file names (case-insensitive)
  const lowerCasePaths = Object.keys(files).map(p => p.toLowerCase());
  const duplicates = lowerCasePaths.filter((p, i, arr) => arr.indexOf(p) !== i);
  if (duplicates.length > 0) {
    errors.push(`Duplicate file names detected: ${duplicates.join(', ')}`);
  }
  
  // Check for invalid characters in file paths
  Object.keys(files).forEach(path => {
    if (/[<>:"|?*]/.test(path)) {
      errors.push(`Invalid characters in file path: "${path}"`);
    }
  });
  
  return {
    isValid: errors.length === 0,
    errors
  };
}
