'use client';

import React from 'react';
import { EnhancedCanvasLayout } from './layout/EnhancedCanvasLayout';
import { useProjectStore } from './state/project-store';

export const EnhancedCanvasPanel: React.FC = () => {
  React.useEffect(() => {
    const store = useProjectStore.getState();
    // Check if any files exist (array length)
    if (store.files.length === 0) {
      if (typeof store.createFile === 'function') {
        // Create default files – third argument is `isFolder` (false for files)
        store.createFile('app/page.tsx', defaultHomePage, false);
        store.createFile('app/globals.css', defaultCss, false);
      } else {
        console.warn('createFile method not available');
      }
    }
  }, []);

  return <EnhancedCanvasLayout />;
};

const defaultHomePage = `export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 to-black text-white p-8">
      <div className="max-w-6xl mx-auto">
        <header className="mb-12">
          <h1 className="text-4xl font-bold mb-2">🚀 AI Meta Factory</h1>
          <p className="text-gray-400">Full-stack application generated with AI</p>
        </header>
        <div className="grid md:grid-cols-3 gap-6 mb-12">
          <div className="bg-gray-800/50 backdrop-blur-sm p-6 rounded-xl border border-gray-700">
            <div className="text-2xl mb-4">⚡</div>
            <h3 className="font-semibold mb-2">AI-Powered</h3>
            <p className="text-gray-400 text-sm">Generated by advanced AI models with production-ready code</p>
          </div>
          <div className="bg-gray-800/50 backdrop-blur-sm p-6 rounded-xl border border-gray-700">
            <div className="text-2xl mb-4">🎨</div>
            <h3 className="font-semibold mb-2">Modern Stack</h3>
            <p className="text-gray-400 text-sm">Built with Next.js, TypeScript, Tailwind CSS, and best practices</p>
          </div>
          <div className="bg-gray-800/50 backdrop-blur-sm p-6 rounded-xl border border-gray-700">
            <div className="text-2xl mb-4">🚀</div>
            <h3 className="font-semibold mb-2">Ready to Deploy</h3>
            <p className="text-gray-400 text-sm">One-click deployment to Vercel, Netlify, or your own infrastructure</p>
          </div>
        </div>
        <div className="bg-gradient-to-r from-blue-900/30 to-purple-900/30 border border-blue-700/30 rounded-xl p-6">
          <h2 className="text-xl font-semibold mb-4">Getting Started</h2>
          <p className="text-gray-300 mb-4">Edit this page in the code editor to customize your application. Use the AI Assistant to generate new components or features.</p>
          <div className="flex space-x-4">
            <button className="px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg">Explore Components</button>
            <button className="px-4 py-2 bg-gray-800 hover:bg-gray-700 border border-gray-700 rounded-lg">View Documentation</button>
          </div>
        </div>
      </div>
    </div>
  );
}`;

const defaultCss = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 255, 255, 255;
  --background-start-rgb: 15, 23, 42;
  --background-end-rgb: 0, 0, 0;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(to bottom, transparent, rgb(var(--background-end-rgb))) rgb(var(--background-start-rgb));
}

::-webkit-scrollbar { width: 10px; }
::-webkit-scrollbar-track { background: rgba(255, 255, 255, 0.05); }
::-webkit-scrollbar-thumb { background: rgba(255, 255, 255, 0.2); border-radius: 5px; }
::-webkit-scrollbar-thumb:hover { background: rgba(255, 255, 255, 0.3); }`;
