"use client";

import { useState, useEffect } from 'react';
import { EnhancedFileTree } from './EnhancedFileTree';
import { EnhancedCodeEditor } from './EnhancedCodeEditor';
import { EnhancedCanvasControls } from './EnhancedCanvasControls';
import { OpenAIService } from '@/lib/ai/openai-service';
import { RealGitHubHandler } from '@/lib/github/real-handler';
import { EnhancedProjectExporter } from '@/lib/export/enhanced-exporter';
import toast from 'react-hot-toast';

interface EnhancedCanvasPanelProps {
  initialFiles: Record<string, string>;
  onFilesChange: (files: Record<string, string>) => void;
  stack: string;
  database: string;
  gitProvider: string;
  projectName: string;
  session: any;
}

export function EnhancedCanvasPanel({
  initialFiles,
  onFilesChange,
  stack,
  database,
  gitProvider,
  projectName: initialProjectName,
  session
}: EnhancedCanvasPanelProps) {
  const [files, setFiles] = useState<Record<string, string>>(initialFiles);
  const [activeFile, setActiveFile] = useState<string | null>(Object.keys(initialFiles)[0] || null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [projectName, setProjectName] = useState(initialProjectName);

  // Sync files with parent
  useEffect(() => {
    onFilesChange(files);
  }, [files, onFilesChange]);

  // Initialize real services
  const aiService = new OpenAIService();
  const projectExporter = new EnhancedProjectExporter();

  const handleFileSelect = (path: string) => {
    setActiveFile(path);
  };

  const handleFileChange = (path: string, content: string) => {
    const newFiles = { ...files, [path]: content };
    setFiles(newFiles);
  };

  const handleFileDelete = (path: string) => {
    const newFiles = { ...files };
    delete newFiles[path];
    setFiles(newFiles);
    
    if (activeFile === path) {
      setActiveFile(Object.keys(newFiles)[0] || null);
    }
    
    toast.success(`Deleted ${path.split('/').pop()}`);
  };

  const handleFileCreate = (type: 'file' | 'folder', path: string) => {
    if (type === 'file') {
      const content = getDefaultContent(path);
      const newFiles = { ...files, [path]: content };
      setFiles(newFiles);
      setActiveFile(path);
      toast.success(`Created ${path}`);
    } else {
      // For folders, create an index file
      const folderPath = `${path}/index.ts`;
      const content = `// Auto-generated folder index file`;
      const newFiles = { ...files, [folderPath]: content };
      setFiles(newFiles);
      toast.success(`Created folder ${path}`);
    }
  };

  const handleFileUpload = async (fileList: FileList) => {
    const newFiles = { ...files };
    
    for (const file of Array.from(fileList)) {
      const content = await file.text();
      newFiles[file.name] = content;
    }
    
    setFiles(newFiles);
    toast.success(`Uploaded ${fileList.length} file(s)`);
  };

  const getDefaultContent = (path: string): string => {
    const ext = path.split('.').pop()?.toLowerCase();
    
    switch (ext) {
      case 'tsx':
        return `import React from 'react';

export default function ${path.split('/').pop()?.split('.')[0] || 'Component'}() {
  return (
    <div>
      <h1>New Component</h1>
      <p>Start editing this component</p>
    </div>
  );
}`;
      case 'ts':
        return `// TypeScript file: ${path.split('/').pop()}

export const example = "Hello, World!";`;
      case 'json':
        return '{\n  "name": "example",\n  "version": "1.0.0"\n}';
      default:
        return `// ${path.split('/').pop()}\n// Created with AI Meta Factory`;
    }
  };

  const handleAIRegenerate = async () => {
    if (!activeFile) {
      toast.error('No file selected');
      return;
    }
    
    setIsGenerating(true);
    try {
      const result = await aiService.regenerateWithAI({
        filePath: activeFile,
        currentCode: files[activeFile],
        originalCode: files[activeFile],
        changes: ['Improve code quality', 'Add comments', 'Optimize structure'],
        context: { stack, database, feature: 'regeneration' }
      });

      const newFiles = { ...files, [activeFile]: result.generatedCode };
      setFiles(newFiles);
      toast.success('AI enhanced code successfully!');
    } catch (error: any) {
      console.error('AI Error:', error);
      toast.error(`AI error: ${error.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleExportProject = async () => {
    try {
      await projectExporter.exportAsZip({
        projectName,
        stack,
        database,
        files,
        description: 'Generated by AI Meta Factory'
      });
      toast.success('Project exported as ZIP!');
    } catch (error: any) {
      toast.error(`Export failed: ${error.message}`);
    }
  };

  const handlePushToGitHub = async () => {
    if (!session?.accessToken) {
      toast.error('Please sign in with GitHub first');
      return;
    }

    setIsGenerating(true);
    try {
      const githubHandler = new RealGitHubHandler(session.accessToken);
      
      const result = await githubHandler.pushToGitHub({
        owner: session.user?.name || 'user',
        repo: projectName,
        commitMessage: 'Initial commit from AI Meta Factory',
        files: Object.entries(files).map(([path, content]) => ({
          path,
          content
        })),
        createRepo: true,
        isPrivate: false
      });

      if (result.success) {
        toast.success(
          <div>
            Successfully pushed to GitHub!{' '}
            <a href={result.repoUrl} target="_blank" rel="noopener noreferrer" className="underline">
              View Repository
            </a>
          </div>
        );
      } else {
        toast.error(result.error || 'Failed to push to GitHub');
      }
    } catch (error: any) {
      console.error('GitHub Error:', error);
      toast.error(`GitHub error: ${error.message}`);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="h-[600px] bg-gray-950 text-gray-100 flex flex-col rounded-xl border border-gray-800 overflow-hidden">
      {/* Top Bar */}
      <div className="px-6 py-4 border-b border-gray-800 bg-gray-900/80">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <h1 className="text-lg font-bold">
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">
                Enhanced Canvas
              </span>
            </h1>
            <div className="flex gap-2">
              <span className="px-3 py-1 bg-blue-900/40 text-blue-300 text-sm rounded-full">
                {stack.toUpperCase()}
              </span>
              <span className="px-3 py-1 bg-green-900/40 text-green-300 text-sm rounded-full">
                {database.toUpperCase()}
              </span>
              <span className="px-3 py-1 bg-gray-800 text-gray-300 text-sm rounded-full">
                {gitProvider.toUpperCase()}
              </span>
            </div>
          </div>
          
          <div className="flex items-center gap-4">
            <div className="text-sm text-gray-400">
              <span className="font-medium">{Object.keys(files).length} files</span>
              <span className="mx-2">•</span>
              <span>{Object.values(files).reduce((sum, c) => sum + c.split('\n').length, 0)} lines</span>
            </div>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left Sidebar - File Tree */}
        <div className="w-64 border-r border-gray-800 flex flex-col">
          <EnhancedFileTree
            files={files}
            onFileSelect={handleFileSelect}
            onFileChange={handleFileChange}
            onFileDelete={handleFileDelete}
            onFileCreate={handleFileCreate}
            onFileUpload={handleFileUpload}
            activeFile={activeFile}
          />
        </div>

        {/* Middle - Code Editor */}
        <div className="flex-1 flex flex-col">
          <EnhancedCodeEditor
            files={files}
            onFileChange={handleFileChange}
            activeFile={activeFile}
          />
        </div>

        {/* Right Sidebar - Controls & AI */}
        <div className="w-80 border-l border-gray-800">
          <EnhancedCanvasControls
            onAIRegenerate={handleAIRegenerate}
            onExportProject={handleExportProject}
            onPushToGitHub={handlePushToGitHub}
            isGenerating={isGenerating}
            projectName={projectName}
            onProjectNameChange={setProjectName}
            stack={stack}
            onStackChange={() => {}}
            database={database}
            onDatabaseChange={() => {}}
            gitProvider={gitProvider}
            onGitProviderChange={() => {}}
            session={session}
          />
        </div>
      </div>
    </div>
  );
}
