"use client";

import { useState } from 'react';
import { X, Sparkles } from 'lucide-react';

interface AIPanelProps {
  onClose: () => void;
  onGenerate: (code: string) => void;
}

export default function AIPanel({ onClose, onGenerate }: AIPanelProps) {
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [outputType, setOutputType] = useState<'react' | 'full-app' | 'apk'>('react');

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    
    setIsGenerating(true);
    
    try {
      // MOCK AI PIPELINE - Replace with actual API calls
      const mockAIPipeline = async (userPrompt: string, type: string) => {
        // Simulate API delay
        await new Promise(resolve => setTimeout(resolve, 2000));
        
        // Mock response based on prompt
        const mockComponents = {
          react: `
            <div className="p-6 bg-white rounded-xl shadow-lg">
              <h2 className="text-2xl font-bold mb-4">${userPrompt}</h2>
              <p className="text-gray-600 mb-4">This component was generated by AI</p>
              <button className="px-4 py-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg hover:opacity-90">
                Generated Action
              </button>
            </div>
          `,
          'full-app': '// Full React app structure with components, routing, and state management',
          apk: '// Android APK configuration and build files'
        };
        
        return mockComponents[type as keyof typeof mockComponents] || mockComponents.react;
      };
      
      const generatedCode = await mockAIPipeline(prompt, outputType);
      onGenerate(generatedCode);
      
    } catch (error) {
      console.error('AI generation failed:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl w-full max-w-2xl max-h-[80vh] flex flex-col">
        {/* Header */}
        <div className="p-6 border-b flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Sparkles className="h-6 w-6 text-purple-600" />
            <h2 className="text-xl font-bold">AI Component Generator</h2>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg">
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 flex-1 overflow-auto">
          <div className="space-y-6">
            {/* Output Type Selection */}
            <div>
              <label className="block text-sm font-medium mb-3">
                What would you like to build?
              </label>
              <div className="grid grid-cols-3 gap-3">
                {[
                  { id: 'react', label: 'React Component', icon: '⚛️' },
                  { id: 'full-app', label: 'Full Web App', icon: '🌐' },
                  { id: 'apk', label: 'APK (Mobile)', icon: '📱' }
                ].map((type) => (
                  <button
                    key={type.id}
                    onClick={() => setOutputType(type.id as any)}
                    className={`p-4 border rounded-lg flex flex-col items-center gap-2 ${
                      outputType === type.id 
                        ? 'border-blue-500 bg-blue-50' 
                        : 'hover:bg-gray-50'
                    }`}
                  >
                    <span className="text-2xl">{type.icon}</span>
                    <span className="text-sm font-medium">{type.label}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* Prompt Input */}
            <div>
              <label className="block text-sm font-medium mb-2">
                Describe what you want to build:
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="Example: A user profile card with avatar, name, bio, and follow button..."
                className="w-full h-32 p-4 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                disabled={isGenerating}
              />
              <div className="mt-2 text-sm text-gray-500">
                Be as detailed as possible for better results
              </div>
            </div>

            {/* AI Pipeline Preview */}
            <div className="bg-gray-50 rounded-lg p-4">
              <h4 className="font-medium mb-3">AI Pipeline Status</h4>
              <div className="space-y-2">
                {[
                  { name: 'OpenAI', status: 'Generating ideas...', color: 'text-green-600' },
                  { name: 'DeepSeek', status: 'Converting to code...', color: 'text-blue-600' },
                  { name: 'Gemini', status: 'Optimizing & checking safety...', color: 'text-purple-600' }
                ].map((stage, idx) => (
                  <div key={stage.name} className="flex items-center gap-3">
                    <div className={`h-2 w-2 rounded-full ${stage.color.replace('text', 'bg')}`}></div>
                    <span className="text-sm">{stage.name}</span>
                    <span className="text-sm text-gray-500 ml-auto">
                      {isGenerating ? stage.status : 'Ready'}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t">
          <div className="flex justify-end gap-3">
            <button
              onClick={onClose}
              className="px-6 py-2 border rounded-lg hover:bg-gray-50"
              disabled={isGenerating}
            >
              Cancel
            </button>
            <button
              onClick={handleGenerate}
              disabled={!prompt.trim() || isGenerating}
              className="px-6 py-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-lg hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
            >
              {isGenerating ? (
                <>
                  <div className="h-4 w-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4" />
                  Generate Component
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
