"use client";

import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { StackConfig } from '../types';

export const detectLanguage = (path: string): string => {
  const extension = path.split('.').pop()?.toLowerCase();
  switch (extension) {
    case 'ts': case 'tsx': return 'typescript';
    case 'js': case 'jsx': return 'javascript';
    case 'py': return 'python';
    case 'dart': return 'dart';
    case 'css': case 'scss': return 'css';
    case 'json': return 'json';
    case 'yaml': case 'yml': return 'yaml';
    case 'md': return 'markdown';
    case 'html': return 'html';
    case 'sql': return 'sql';
    default: return 'text';
  }
};

export interface FileData {
  content: string;
  language: string;
  lastModified: string;
  aiGenerated: boolean;
  aiContext?: {
    prompt: string;
    timestamp: string;
  };
}

export interface ProjectState {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  stack: StackConfig;
  files: Record<string, FileData>;
  activeFile: string | null;
  aiContext: {
    generationPrompt: string;
    history: any[];
    suggestions: any[];
  };
  preview: {
    url: string | null;
    status: 'idle' | 'building' | 'running' | 'error';
    logs: string[];
  };
  export: {
    status: 'idle' | 'exporting' | 'uploading' | 'complete';
    url: string | null;
    size: number;
  };
}

interface ProjectStore extends ProjectState {
  // File Actions
  setFile: (path: string, content: string, aiGenerated?: boolean) => void;
  createFile: (path: string, content?: string, aiGenerated?: boolean) => void;
  deleteFile: (path: string) => void;
  renameFile: (oldPath: string, newPath: string) => void;
  duplicateFile: (path: string) => void;
  updateFile: (path: string, content: string) => void;
  removeFile: (path: string) => void;
  copyFile: (path: string) => void;
  moveFile: (oldPath: string, newPath: string) => void;
  
  // Project Actions
  setActiveFile: (path: string | null) => void;
  setName: (name: string) => void;
  setStack: (stack: Partial<StackConfig>) => void;
  updatePreview: (preview: Partial<ProjectState['preview']>) => void;
  exportProject: () => Promise<void>;
  resetProject: () => void;
  
  // Utilities
  getFileTree: () => any;
  searchFiles: (query: string) => { path: string; name: string }[];
}

const defaultFiles: Record<string, FileData> = {
  'README.md': {
    content: '# AI Generated Project\n\nThis project was generated by AI Meta Factory.',
    language: 'markdown',
    lastModified: new Date().toISOString(),
    aiGenerated: true
  },
  'src/app/page.tsx': {
    content: `export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-4xl font-bold mb-4">Welcome to AI Meta Factory</h1>
      <p className="text-gray-400">Start building your amazing project!</p>
    </main>
  );
}`,
    language: 'typescript',
    lastModified: new Date().toISOString(),
    aiGenerated: true
  },
  'src/app/globals.css': {
    content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 255, 255, 255;
  --background-start-rgb: 0, 0, 0;
  --background-end-rgb: 0, 0, 0;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}`,
    language: 'css',
    lastModified: new Date().toISOString(),
    aiGenerated: true
  }
};

export const useProjectStore = create<ProjectStore>()(
  persist(
    (set, get) => ({
      // Initial state
      id: `project-${Date.now()}`,
      name: 'New Project',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      stack: {
        frontend: 'nextjs',
        backend: 'nodejs',
        database: 'supabase',
        gitProvider: 'github'
      },
      files: defaultFiles,
      activeFile: 'src/app/page.tsx',
      aiContext: {
        generationPrompt: '',
        history: [],
        suggestions: []
      },
      preview: {
        url: null,
        status: 'idle',
        logs: []
      },
      export: {
        status: 'idle',
        url: null,
        size: 0
      },

      // File Actions Implementation
      setFile: (path, content, aiGenerated = false) => {
        set((state) => {
          const language = detectLanguage(path);
          const files = { ...state.files };
          
          files[path] = {
            content,
            language,
            lastModified: new Date().toISOString(),
            aiGenerated
          };
          
          return {
            files,
            updatedAt: new Date().toISOString(),
            activeFile: state.activeFile === path ? path : state.activeFile
          };
        });
      },
      
      createFile: (path, content = '', aiGenerated = false) => {
        set((state) => {
          const language = detectLanguage(path);
          const files = { ...state.files };
          
          if (files[path]) {
            return state;
          }
          
          files[path] = {
            content,
            language,
            lastModified: new Date().toISOString(),
            aiGenerated
          };
          
          return {
            files,
            activeFile: path,
            updatedAt: new Date().toISOString()
          };
        });
      },
      
      deleteFile: (path) => {
        set((state) => {
          const files = { ...state.files };
          delete files[path];
          
          let activeFile = state.activeFile;
          if (activeFile === path) {
            const remainingFiles = Object.keys(files);
            activeFile = remainingFiles.length > 0 ? remainingFiles[0] : null;
          }
          
          return {
            files,
            activeFile,
            updatedAt: new Date().toISOString()
          };
        });
      },
      
      renameFile: (oldPath, newPath) => {
        set((state) => {
          const files = { ...state.files };
          const fileData = files[oldPath];
          
          if (!fileData) {
            console.warn(`File ${oldPath} does not exist`);
            return state;
          }
          
          delete files[oldPath];
          files[newPath] = {
            ...fileData,
            lastModified: new Date().toISOString()
          };
          
          return {
            files,
            activeFile: state.activeFile === oldPath ? newPath : state.activeFile,
            updatedAt: new Date().toISOString()
          };
        });
      },
      
      duplicateFile: (path) => {
        set((state) => {
          const files = { ...state.files };
          const fileData = files[path];
          
          if (!fileData) {
            console.warn(`File ${path} does not exist`);
            return state;
          }
          
          const extension = path.split('.').pop();
          const baseName = path.replace(`.${extension}`, '');
          let newPath = '';
          let counter = 1;
          
          do {
            newPath = `${baseName}-copy${counter > 1 ? counter : ''}.${extension}`;
            counter++;
          } while (files[newPath]);
          
          files[newPath] = {
            ...fileData,
            lastModified: new Date().toISOString(),
            aiGenerated: false
          };
          
          return {
            files,
            activeFile: newPath,
            updatedAt: new Date().toISOString()
          };
        });
      },
      
      updateFile: (path, content) => {
        get().setFile(path, content, false);
      },
      
      removeFile: (path) => {
        get().deleteFile(path);
      },
      
      copyFile: (path) => {
        get().duplicateFile(path);
      },
      
      moveFile: (oldPath, newPath) => {
        set((state) => {
          const files = { ...state.files };
          const fileData = files[oldPath];
          
          if (!fileData) {
            console.warn(`File ${oldPath} does not exist`);
            return state;
          }
          
          delete files[oldPath];
          files[newPath] = {
            ...fileData,
            lastModified: new Date().toISOString()
          };
          
          return {
            files,
            activeFile: state.activeFile === oldPath ? newPath : state.activeFile,
            updatedAt: new Date().toISOString()
          };
        });
      },
      
      // Project Actions Implementation
      setActiveFile: (path) => {
        set({ 
          activeFile: path,
          updatedAt: new Date().toISOString()
        });
      },
      
      setName: (name) => {
        set({
          name,
          updatedAt: new Date().toISOString()
        });
      },
      
      setStack: (newStack) => {
        set((state) => ({
          stack: { ...state.stack, ...newStack },
          updatedAt: new Date().toISOString()
        }));
      },
      
      updatePreview: (preview) => {
        set((state) => ({
          preview: { ...state.preview, ...preview },
          updatedAt: new Date().toISOString()
        }));
      },
      
      exportProject: async () => {
        const state = get();
        console.log('Exporting project:', state.id);
        return Promise.resolve();
      },
      
      resetProject: () => {
        set({
          files: defaultFiles,
          activeFile: 'src/app/page.tsx',
          updatedAt: new Date().toISOString()
        });
      },
      
      // Utilities Implementation
      getFileTree: () => {
        const files = get().files;
        const tree: any = {};
        
        Object.keys(files).forEach(path => {
          const parts = path.split('/');
          let current = tree;
          
          parts.forEach((part, index) => {
            if (!current[part]) {
              current[part] = index === parts.length - 1 
                ? { type: 'file', path } 
                : { type: 'folder', children: {} };
            }
            if (index !== parts.length - 1) {
              current = current[part].children;
            }
          });
        });
        
        return tree;
      },
      
      searchFiles: (query) => {
        const files = get().files;
        const results: { path: string; name: string }[] = [];
        
        Object.keys(files).forEach(path => {
          const name = path.split('/').pop() || '';
          if (name.toLowerCase().includes(query.toLowerCase()) || 
              path.toLowerCase().includes(query.toLowerCase())) {
            results.push({ path, name });
          }
        });
        
        return results;
      }
    }),
    {
      name: 'project-storage',
      storage: createJSONStorage(() => localStorage),
      partialize: (state) => ({
        id: state.id,
        name: state.name,
        files: state.files,
        stack: state.stack,
        activeFile: state.activeFile
      })
    }
  )
);
