
android {
    defaultConfig {
        ndk {
        }
        ndk {
        }
        externalNativeBuild {
            cmake {
                cppFlags "-O2 -std=c++17"
                arguments "-DANDROID_ABI=arm64-v8a", "-DANDROID_STL=c++_shared"
            }
        }
    }
    externalNativeBuild {
        cmake {
            path file("$projectDir/src/main/cpp/CMakeLists.txt")
            version "3.22.1"
        }
    }
}
